### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by netwurk** [jmacul2/raven-cfml#6]
It appears that raven-cfml client no longer works. Sentry "disabled very old python (and similar) SDKs using an insecure protocol..." on or around 8/4 - https://twitter.com/getsentry/status/628673049357713408

Since then, my servers have stopped reporting errors - which I assume is related.

**Comment by docapotamus** [comment]
@netwurk I have just set this up as I am now using CFML at a new job and it works fine for me. Maybe there is something else wrong.

**Comment by netwurk** [comment]
That's possible. It just stopped working for me on a few servers around the same time Sentry made upgrades, so I thought it was likely related. I actually moved from Sentry to Raygun in order to get things working again during that point in time.
